// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Ringkas.Api.Data;

#nullable disable

namespace Ringkas.Api.Migrations;

[DbContext(typeof(RingkasDbContext))]
[Migration("20260901143000_AddOpenCodeZenProvider")]
partial class AddOpenCodeZenProvider
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
